remove tabs

diff --git a/mkcjail b/mkcjail
--- a/mkcjail
+++ b/mkcjail
@@ -12,15 +12,15 @@ usage() {
 
 while getopts 'c:s' arg; do
     case $arg in
-	c)
-	    CONFFILE=$OPTARG
-	    ;;
-	s)
-	    STARTSHELL=1
-	    ;;
-	\?)
-	    usage
-	    ;;
+        c)
+            CONFFILE=$OPTARG
+            ;;
+        s)
+            STARTSHELL=1
+            ;;
+        \?)
+            usage
+            ;;
     esac
 done
 
@@ -43,9 +43,9 @@ cleanup() {
     trap - 0
     local n=${#MOUNTED[@]}
     while [[ $n -gt 0 ]]; do
-	n=$((n - 1))
-	umount -l "${MOUNTED[$n]}"
-	unset MOUNTED[$n]
+        n=$((n - 1))
+        umount -l "${MOUNTED[$n]}"
+        unset MOUNTED[$n]
     done
     exit
 }
@@ -54,9 +54,9 @@ bind_dirs() {
     trap 'cleanup' 0 2 15
 
     for dir in /proc /sys /dev /dev/pts /dev/shm; do
-	mkdir -p "$DESTDIR/${dir#/}"
-	MOUNTED[${#MOUNTED[@]}]="$DESTDIR/${dir#/}"
-	mount -B "$dir" "$DESTDIR/${dir#/}"
+        mkdir -p "$DESTDIR/${dir#/}"
+        MOUNTED[${#MOUNTED[@]}]="$DESTDIR/${dir#/}"
+        mount -B "$dir" "$DESTDIR/${dir#/}"
     done
 
     mkdir -p "$DESTDIR"/tmp
@@ -66,8 +66,8 @@ bind_dirs() {
 
 bind_files() {
     for file in /etc/resolv.conf /etc/pacman.d/mirrorlist; do
-	MOUNTED[${#MOUNTED[@]}]="$DESTDIR/${file}"
-	mount -B "$file" "$DESTDIR/${file}"
+        MOUNTED[${#MOUNTED[@]}]="$DESTDIR/${file}"
+        mount -B "$file" "$DESTDIR/${file}"
     done
 }
 
@@ -88,12 +88,12 @@ init_dest() {
 
     rpacman -S --needed base base-devel
     if [[ ${#PACKAGES[@]} > 0 ]]; then
-	rpacman -S --needed "${PACKAGES[@]}"
+        rpacman -S --needed "${PACKAGES[@]}"
     fi
 
     grep -q '^[^#]' "$DESTDIR/etc/pacman.d/mirrorlist" \
-	|| sed -ie "\|http://mirrors.cat.pdx.edu/|s/^#//" \
-	    "$DESTDIR/etc/pacman.d/mirrorlist"
+        || sed -ie "\|http://mirrors.cat.pdx.edu/|s/^#//" \
+            "$DESTDIR/etc/pacman.d/mirrorlist"
 
     rm -r "$DESTDIR/var/tmp"
     ln -s ../tmp "$DESTDIR/var/tmp"
@@ -105,23 +105,23 @@ setup_yaourt() {
     local pkg
 
     if rpacman -Qmq | egrep -q '^yaourt$'; then
-	return
+        return
     fi
 
     chroot "$DESTDIR" sh -c \
-	"pacman-key --init"
+        "pacman-key --init"
 
     chroot "$DESTDIR" sh -c \
-	"yes | pacman-key --populate archlinux"
+        "yes | pacman-key --populate archlinux"
     
     chroot "$DESTDIR" sh -c \
         "pacman-key --lsign-key 1EB2638FF56C0C53"
 
     for pkg in package-query yaourt; do
-	wget -O- "http://aur.archlinux.org/packages/${pkg:0:2}/${pkg}/${pkg}.tar.gz" \
-	    | tar -C "$DESTDIR/tmp" -xzf -
-	chroot "$DESTDIR" sh -c \
-	    "set -x; cd /tmp/$pkg && makepkg --asroot -si --noconfirm"
+        wget -O- "http://aur.archlinux.org/packages/${pkg:0:2}/${pkg}/${pkg}.tar.gz" \
+            | tar -C "$DESTDIR/tmp" -xzf -
+        chroot "$DESTDIR" sh -c \
+            "set -x; cd /tmp/$pkg && makepkg --asroot -si --noconfirm"
     done
 }
 
@@ -130,18 +130,18 @@ setup_aur() {
 
     local -A installed
     while read pkg; do
-	installed[$pkg]=1
+        installed[$pkg]=1
     done < <(rpacman -Qmq)
 
     local -a toinstall
     for pkg in "${AUR[@]}"; do
-	if [[ -z ${installed[$pkg]} ]]; then
-	    toinstall[${#toinstall[@]}]=$pkg
-	fi
+        if [[ -z ${installed[$pkg]} ]]; then
+            toinstall[${#toinstall[@]}]=$pkg
+        fi
     done
 
     if [[ ${#toinstall[@]} > 0 ]]; then
-	HOME=/root chroot "$DESTDIR" yaourt --noconfirm -S "${toinstall[@]}"
+        HOME=/root chroot "$DESTDIR" yaourt --noconfirm -S "${toinstall[@]}"
     fi
     HOME=/root chroot "$DESTDIR" yaourt --noconfirm -Sau
 }
@@ -149,17 +149,17 @@ setup_aur() {
 setup_init() {
     local dir=${0%/*} init foundit=
     for init in "$dir/cjail-init" /usr/lib/cjail/init; do
-	if [[ -x $init ]]; then
-	    foundit=1
-	    cp "$init" "$DESTDIR"/init
-	    chmod 04500 "$DESTDIR"/init
-	    break
-	fi
+        if [[ -x $init ]]; then
+            foundit=1
+            cp "$init" "$DESTDIR"/init
+            chmod 04500 "$DESTDIR"/init
+            break
+        fi
     done
 
     if [[ -z $foundit ]]; then
-	echo "cannot find cjail-init" >&2
-	exit 1
+        echo "cannot find cjail-init" >&2
+        exit 1
     fi
 }
 
@@ -170,8 +170,8 @@ fi
 
 if [[ -n $STARTSHELL ]]; then
     if ! test -r "$BASEDIR/.cjail"; then
-	echo "$BASEDIR: not a cjail (must create it before using -s)" >&2
-	exit 1
+        echo "$BASEDIR: not a cjail (must create it before using -s)" >&2
+        exit 1
     fi
     bind_dirs
     bind_files
